### ISSUE TITLE
bug(file-picker): path is not absolute on Android

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-plugins#11]
**Is your feature request related to a problem? Please describe:**

For example, some paths returned by `pickFiles(...)` look like `/document/image/1234`.

Related to https://stackoverflow.com/questions/13209494/how-to-get-the-full-file-path-from-uri

**Describe the solution you'd like:**

The path should be absolute, e.g. `/storage/emulated/0/DCIM/Camera/IMG_20220808_1234.jpg`.

**Describe alternatives you've considered:**

**Additional context:**

Maybe also related: https://github.com/hiddentao/cordova-plugin-filepath

**Comment by nvahalik** [comment]
I'm not the author of the plugin, but this is actually the way it seems like it should work. When you want to load data from other providers, rather than throwing around full URLs, which requires you to have full access to the file system, you get back a URI which should have `content://` included with it.

Some of the plugins which you're using will need to be updated to use those `content://` URIs rather than `file://` URIs. We've had to do this with a couple of ours.

I've seen *some* folks say that you can get a legacy `file://` URI but it isn't guaranteed because the provider would have to provide it.

**Comment by robingenz** [comment]
@nvahalik Thank you for pointing that out. I have had to look into this topic myself over the last few weeks.

The `content://` URIs are indeed the way to go under Android. For this reason, I am closing this issue.
