### ISSUE TITLE
feat(file-picker): iOS preparing video progress

### ISSUE THREAD

**Issue by massimoliani** [capawesome-team/capacitor-plugins#12]
Hi,

We are using file picker to pick media files (video and picture).

In a previouse version we use the html input file to select media files from an iOS device and iOS on some file let show a progress dialog for preparing file. Now we are using the file picker with capacitor 4 (to have native path) and on iOS we can't see anymore the system progress dialog box.

I add a spinner starting at file picker call and ending at then or catch of the picker promise, but I can't show any progress percentage.

Is there a way to enable in file picker the system progress dialog?
Or to have a call back about preparing progress? 

To show to final user the app is not blocked and is going on preparing file will be fine to avoid user to stop the app thinking to the app blocked. 

Thank you in advance.

**Comment by skmbr** [comment]
Just wondering if this is something that is likely to be added any time soon?

I've implemented a loading spinner using `pickerDismissed` as suggested, but I've already had two beta testers report "bugs" along the lines of "gets stuck on loading spinner when I open a video".

In both cases it turned out that they were opening large videos that took over a minute to process, but were giving up because they thought nothing was happening. :(

I notice on Android that there is still a "Processing" progress bar when opening a video.

**Comment by robingenz** [comment]
@skmbr I'm really busy this year until the end of August and won't be able to work on this issue until then. PRs are welcome and will be reviewed. I definitely plan to resolve this issue this year.

**Comment by massimoliani** [comment]
@skmbr I add a spinner before opening the picker and then the spinner stop when the picker close.

Before using the plugin I used HTML input file and then write the file to a local app folder to use as native file and be able to use whenever I need especially if the app is restarted.

The implementation for the plugin in iOS returned filenames thatr are copy of original image/video in a local app folder, so you can reload it after restarting the app.

On android the result filenmes are content:... style that are avaiable only during the app session, when restarting are no more avaiable. Is like using HTML input file.

Both Android and iOS implement privacy rules to avoid accessing directly to user media.

@robingenz could be possible to add a filesystem copy on Android too, like the iOS implementation? to have the files usable also after a reload of the app?

**Comment by robingenz** [comment]
> @robingenz could be possible to add a filesystem copy on Android too, like the iOS implementation? to have the files usable also after a reload of the app?

Yes, there is already an issue for that: #13

**Comment by skmbr** [comment]
@robingenz Sorry to be a pain but I was just wondering if end of August is still looking probable for looking at this issue?

On average I'm now getting around three people a week contacting me about opening videos "not working" that all turn out to be because they aren't waiting long enough (at least those who get back to me!) but worse is that I've had several negative app store reviews from people saying opening videos "no longer works".

Is there any way I could immediately find out the file size of the video being opened and then maybe I could estimate how long to animate a fake progress bar for?

**Comment by robingenz** [comment]
@skmbr Yes, I'm still trying to look at it in August but I can't promise I'll find a fix right away.

**Comment by skmbr** [comment]
@robingenz Ok, thanks for the update! :)

**Comment by danbunkr** [comment]
@skmbr - I actually had the same issue and was able to solve it by reworking how I handle videos during my "upload process" as I was having the same issue with the videos taking forever to be picked. I'll try and write my steps below in detail:

1.) Add skipTranscoding: true. This is a huge performance gain that off the bat will most likely 10x your performance

```
   const { files } = await FilePicker.pickMedia({
        multiple: true,
        skipTranscoding: true,
      });
      ```
      
      2.) Added this logic. Previously I was transcoding and then reading the entire blob into memory via fetch but now I only fetch the blob once the user hits "upload". For my preview UI I just use this now
      
      ```
                const filePath =
              file.mimeType === FILE_CONTENT_TYPES.HEIC
                ? await FilePicker.convertHeicToJpeg({ path: file.path })
                : file.path;

            const mimeType =
              file.mimeType === FILE_CONTENT_TYPES.HEIC
                ? FILE_CONTENT_TYPES.JPEG
                : file.mimeType;

            const nativeSource = Capacitor.convertFileSrc(
              filePath?.path || filePath
            );

            return {
              thumbnail: nativeSource,
              name: file.name
                ? file.name.replace(new RegExp('.HEIC', 'i'), '.jpeg')
                : null,
              type: mimeType,
              upload_source: UPLOAD_SOURCES.PHOTOS,
              size: file.size,
            };
            ```

**Comment by robingenz** [comment]
I am currently working on this issue and can finally reproduce the it. My mistake was taking an mp4 file that I had downloaded. I can only reproduce it when I select a video that I took with the Camera app on iOS.

Also, I can only reproduce the issue when I set `skipTranscoding` to `false` (related to #42). If I set `skipTranscoding` to `true`, then the Promise is resolved immediately and i can access the file, see the following video.

![RPReplay_Final1697616381](https://github.com/capawesome-team/capacitor-plugins/assets/13857929/4ab0b3d7-5dce-451d-8810-a5e25d6164e2)

Therefore it is not planned to implement a progress bar at the moment, since I assume that the actual issue was the waiting time. With the next major release I will set `skipTranscoding` to `true` by default. However, I am open to other ideas and PRs are also welcome if someone comes up with a better solution.

**Comment by skmbr** [comment]
Hi @robingenz 

Thanks for the update. That seems totally fair.

I've since had another go with updating the plugin and skipTranscoding does now seem to do the job nicely so, as you say, with the waiting time gone the progress indication becomes much less important.

Thanks for all your help!

**Comment by danbunkr** [comment]
@robingenz only issue with the skip transcoding true I've ran into since implementing it is that when you upload a file on IOS with skip transcoding true when you go to generate a thumbnail on Android it won't work due to the video itself not been long transcoded to work cross platform

**Comment by robingenz** [comment]
@danbunkr Thanks for sharing! I did not know that. Feel free to create a separate issue where we can discuss possible solutions. Maybe we could add a new method, similar to `convertHeicToJpeg(...)`. A reproducible example with a demo file would be good.
