### ISSUE TITLE
feat(nfc): Android Beam Message

### ISSUE THREAD

**Issue by dnx-xy** [capawesome-team/capacitor-plugins#126]
Hi Dev,
I was wondering is this plugin capable sending push message from what ever content being sent (Android Beam)

Thanks and regards

**Comment by robingenz** [comment]
I'm closing this issue because Android Beam has been deprecated since Android 10, see [Android Beam deprecation](https://developer.android.com/about/versions/10/behavior-changes-all#beam-deprecation).

However, I have recently added support for HCE: https://github.com/capawesome-team/capacitor-plugins/issues/155#issuecomment-2157753574
