### ISSUE TITLE
feat: Enable (Video) File Streaming from URLs to Improve Preview Experience

### ISSUE THREAD

**Issue by Phil0xFF** [capawesome-team/capacitor-plugins#86]
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [x] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Current problem

Users are encountering inconvenience while attempting to preview large video files. The current system mandates that the entire video file be downloaded before it can be previewed, which results in a suboptimal user experience particularly for large files.

### Preferred solution

Users should be able to preview video files directly from URLs without the need to download the entire file. Streaming the video for preview can offer a much smoother and faster experience:
Implement a feature that allows video files to be streamed directly from URLs. This will help the user experience by minimizing downtime.

**Comment by robingenz** [comment]
Thank you for this request. I understand the problem but the File Opener plugin is probably the wrong solution for this. It would require a completely different implementation than the current one. I don't know the exact requirements, but for this feature you don't really need a Capacitor plugin. Streaming videos via the WebView should be possible without any problems. Otherwise this feature request would fit better to a video player plugin.
For this reason I close this issue as not planned.
