### ISSUE TITLE
bug: change package name

### ISSUE THREAD

**Issue by luisbytes** [capawesome-team/capacitor-plugins#91]
### Plugin(s)

- [X] Android Foreground Service
- [X] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

The foreground service and battery optimization plugins are with the prefix @capawesome-team/

### Expected behavior

The prefix is expected to be this @capawesome/

### Reproduction

https://www.npmjs.com/package/@capawesome-team/capacitor-android-foreground-service

### Steps to reproduce

1. npm i @capawesome-team/capacitor-android-foreground-service

### Capacitor doctor

https://www.npmjs.com/package/@capawesome-team/capacitor-android-foreground-service

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
The prefix is correct. "@capawesome-team" is used by packages which are (also) available via the GitHub package registry. These are mostly packages which are only accessible to insider sponsors.

**Comment by robingenz** [comment]
You mean the public npm registry? Yes, but we still distribute the packages to GitHub Packages and we cannot use two different package names because the plugin `*.podspec` file name must correspond to the package name. 
Furthermore, we would then have to deliver all packages via GitHub Packages, otherwise the following rule would no longer be possible if you also want to install other Capawesome packages:

```
@capawesome:registry=https://npm.pkg.github.com
```

What is the problem with the name?
